### ISSUE TITLE
View Important Disclosures Links to nowhere

### ISSUE THREAD

**Issue by AgeManning** [sigp/siren#106]
In the Validator Health Check the "View Important Disclosures" doesn't link to anywhere or doesn't work from the electron app. Perhaps we either remove it or grey it out for the beta.

**Comment by rickimoore** [comment]
<img width="925" alt="Screenshot 2023-02-16 at 14 05 29" src="https://user-images.githubusercontent.com/12932889/219386444-1acfd369-5264-42ca-978e-5dc664839912.png">

I have made the following modals for disclosures, we only need the correct copy for this feature to be complete.

**Comment by rickimoore** [comment]
handled in #115
