### ISSUE TITLE
Missing various Tooltip text copy

### ISSUE THREAD

**Issue by rickimoore** [sigp/siren#97]
I attached screenshots of tooltips placed in the ui by design, however none have copy text. Please leave a comment with an appropriate text below.

<img width="499" alt="Screenshot 2023-01-31 at 10 46 03" src="https://user-images.githubusercontent.com/12932889/215829337-dd7e643a-8ed4-4c0b-b5c7-c642395a85bc.png">

<img width="596" alt="Screenshot 2023-01-31 at 10 45 06" src="https://user-images.githubusercontent.com/12932889/215829393-2bbc8317-66e0-4e9d-899a-24a6429a6b9d.png">

**Comment by rickimoore** [comment]
I added texts for ETH and USD tooltips...Let me know if you agree or have alternatives.

when user views total earnings...
<img width="632" alt="Screenshot 2023-01-31 at 16 44 50" src="https://user-images.githubusercontent.com/12932889/215829746-9107dcf7-5db7-41b9-9382-fcddf008cc31.png">

when user views an estimate earning timeframe...
<img width="633" alt="Screenshot 2023-01-31 at 16 45 08" src="https://user-images.githubusercontent.com/12932889/215829897-311819d0-3e08-4f40-8917-dca9a2736412.png">

when user views total earnings fiat conversion
<img width="614" alt="Screenshot 2023-01-31 at 16 44 55" src="https://user-images.githubusercontent.com/12932889/215830066-ff56b55d-fd47-455a-9cc8-3d12d2e96f5a.png">

when user is viewing estimate earnings fiat conversion
<img width="630" alt="Screenshot 2023-01-31 at 16 45 15" src="https://user-images.githubusercontent.com/12932889/215830204-bb049c15-f32a-4738-b935-02b250da2257.png">

**Comment by AgeManning** [comment]
From left to right on the main screen:

Process Uptime: "The time that validator client has been running"
Process Uptime: "The time that the beacon node has been running"

At head slot: I think we should change the title of this to: Blocks behind (or Blocks behind current slot, if the text isn't too long). And the tooltip could be:  "Number of slots the beacon node is behind. This indicates if the beacon node is at the head of the chain" <- Can not use the second sentence if its too long. 

Connected Peers: "The number of peers connected to the beacon node"
Participation Rate: "The percentage of active validators that performed their duties last epoch"

**Comment by rickimoore** [comment]
![Screenshot 2023-02-15 at 21 58 35](https://user-images.githubusercontent.com/12932889/219179017-eae3876e-48bb-4c5c-8cda-887addb8e408.png)
@AgeManning can we add some texts here as well?

**Comment by AgeManning** [comment]
Oh yeah. 

So I assume these go under teh question marks that we have there. 
- Protocol: The type of transport, http is default
- Beacon Address: The IP address of the beacon node
- BN Port: The port number of the Beacon Node HTTP API (5052 default). Beacon node should be configured with the --http or --gui flag
- VC Port: The port number of the Validator Client HTTP API (5062 default). 
- Api Token: This is the token emitted by the validator client. Its located by default at `~/.lighthouse/<network>/validators/api-token.txt`

**Comment by rickimoore** [comment]
handled in #111 and #122
